// Publishes reports/report.json to Mongo so the DEPLOYED gateway can serve it
// at GET /evals/report.json.
//
// Why this exists: hygiene git-ignores `reports/`, but the evidence rule says
// the deployed gateway must serve the report. Committing it breaks the first
// rule; not committing it leaves production returning 404, which is what was
// happening. The report travels through the database instead of the repo --
// still generated by eval/build-report.mjs from one real bench run, still
// never hand-edited.
//
// Usage:
//   node publish-report.mjs                    # publish reports/report.json
//   node publish-report.mjs --check            # show what is currently published
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { MongoClient } from "mongodb";

const here = dirname(fileURLToPath(import.meta.url));
const REPORT = resolve(here, "reports/report.json");

const uri = process.env.MONGODB_URI;
if (!uri) {
  console.error("MONGODB_URI is not set. Run with: node --env-file=.env publish-report.mjs");
  process.exit(1);
}

const client = new MongoClient(uri);
await client.connect();
const db = client.db(process.env.MONGODB_DB || "lumina");
const col = db.collection("evalReports");

if (process.argv.includes("--check")) {
  const row = await col.findOne({}, { sort: { publishedAt: -1 } });
  if (!row) console.log("nothing published yet");
  else {
    console.log(`published at ${row.publishedAt?.toISOString?.() ?? "?"}`);
    console.log(`  keys: ${Object.keys(row.report ?? {}).sort().join(", ")}`);
    console.log(`  student: ${row.report?.student ?? "?"}`);
    console.log(`  bench target: ${row.report?.bench?.target ?? "?"}`);
  }
  await client.close();
  process.exit(0);
}

let report;
try {
  report = JSON.parse(await readFile(REPORT, "utf8"));
} catch (err) {
  console.error(`Cannot read ${REPORT}: ${err.message}`);
  console.error("Run the bench, then eval/build-report.mjs, before publishing.");
  await client.close();
  process.exit(1);
}

// A report measured against localhost is not evidence about the deployment,
// and publishing one would quietly put the wrong numbers on /evals.
const target = report?.bench?.target ?? "";
if (/localhost|127\.0\.0\.1/.test(target)) {
  console.error(`Refusing to publish: this report was measured against ${target}.`);
  console.error("Re-run the bench with --target https://<your-gateway> first.");
  await client.close();
  process.exit(1);
}

// Keep history rather than overwriting: the route reads the newest, and an
// older one stays available if a later run turns out to be worse.
await col.insertOne({ report, publishedAt: new Date(), target });
await col.createIndex({ publishedAt: -1 }).catch(() => {});

console.log(`published report measured against ${target}`);
console.log(`  keys: ${Object.keys(report).sort().join(", ")}`);
console.log("\nThe deployed gateway will serve it at GET /evals/report.json.");
await client.close();
